# Generated by Django 4.1.4 on 2023-01-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("highlights", "0005_book_slug_tag_slug_alter_author_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="book_no",
            field=models.CharField(blank=True, default=1, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="highlights",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="highlights.highlight"
            ),
        ),
    ]
