# Generated by Django 4.1.4 on 2023-01-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("highlights", "0006_alter_book_book_no_alter_tag_highlights"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="tag",
            field=models.CharField(
                db_index=True,
                error_messages={"unique": "This tag already exists."},
                max_length=255,
            ),
        ),
    ]
